// Copyright 2025, Reclaim Protocol. Use of this source code is governed by a license that can be found in the LICENSE file.
// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

typealias MessagesBinaryMessenger = any FlutterBinaryMessenger

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum ReclaimApiVerificationExceptionType: Int, CaseIterable {
  case unknown = 0
  case sessionExpired = 1
  case verificationDismissed = 2
  case verificationFailed = 3
  case verificationCancelled = 4
}

enum ReclaimSessionStatus: Int, CaseIterable {
  case uSERSTARTEDVERIFICATION = 0
  case uSERINITVERIFICATION = 1
  case pROOFGENERATIONSTARTED = 2
  case pROOFGENERATIONRETRY = 3
  case pROOFGENERATIONSUCCESS = 4
  case pROOFGENERATIONFAILED = 5
  case pROOFSUBMITTED = 6
  case pROOFSUBMISSIONFAILED = 7
  case pROOFMANUALVERIFICATIONSUBMITTED = 8
  case aIPROOFSUBMITTED = 9
  case uSERINTERACTED = 10
  case uSERTYPED = 11
}

enum ClaimCreationTypeApi: Int, CaseIterable {
  case standalone = 0
  case meChain = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReclaimApiVerificationRequest: Hashable, CustomStringConvertible {
  var appId: String
  var providerId: String
  var secret: String
  var signature: String
  var timestamp: String? = nil
  var context: String
  var sessionId: String
  var parameters: [String: String]
  var providerVersion: ProviderVersionApi? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReclaimApiVerificationRequest? {
    let appId = pigeonVar_list[0] as! String
    let providerId = pigeonVar_list[1] as! String
    let secret = pigeonVar_list[2] as! String
    let signature = pigeonVar_list[3] as! String
    let timestamp: String? = nilOrValue(pigeonVar_list[4])
    let context = pigeonVar_list[5] as! String
    let sessionId = pigeonVar_list[6] as! String
    let parameters = pigeonVar_list[7] as! [String: String]
    let providerVersion: ProviderVersionApi? = nilOrValue(pigeonVar_list[8])

    return ReclaimApiVerificationRequest(
      appId: appId,
      providerId: providerId,
      secret: secret,
      signature: signature,
      timestamp: timestamp,
      context: context,
      sessionId: sessionId,
      parameters: parameters,
      providerVersion: providerVersion
    )
  }
  func toList() -> [Any?] {
    return [
      appId,
      providerId,
      secret,
      signature,
      timestamp,
      context,
      sessionId,
      parameters,
      providerVersion,
    ]
  }
  static func == (lhs: ReclaimApiVerificationRequest, rhs: ReclaimApiVerificationRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.appId, rhs.appId) && MessagesPigeonInternal.deepEquals(lhs.providerId, rhs.providerId) && MessagesPigeonInternal.deepEquals(lhs.secret, rhs.secret) && MessagesPigeonInternal.deepEquals(lhs.signature, rhs.signature) && MessagesPigeonInternal.deepEquals(lhs.timestamp, rhs.timestamp) && MessagesPigeonInternal.deepEquals(lhs.context, rhs.context) && MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.parameters, rhs.parameters) && MessagesPigeonInternal.deepEquals(lhs.providerVersion, rhs.providerVersion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ReclaimApiVerificationRequest")
    MessagesPigeonInternal.deepHash(value: appId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: providerId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: secret, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: signature, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: timestamp, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: context, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: parameters, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: providerVersion, hasher: &hasher)
  }

  public var description: String {
    return "ReclaimApiVerificationRequest(appId: \(String(describing: appId)), providerId: \(String(describing: providerId)), secret: \(String(describing: secret)), signature: \(String(describing: signature)), timestamp: \(String(describing: timestamp)), context: \(String(describing: context)), sessionId: \(String(describing: sessionId)), parameters: \(String(describing: parameters)), providerVersion: \(String(describing: providerVersion)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReclaimApiVerificationException: Hashable, CustomStringConvertible {
  var message: String
  var stackTraceAsString: String
  var type: ReclaimApiVerificationExceptionType


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReclaimApiVerificationException? {
    let message = pigeonVar_list[0] as! String
    let stackTraceAsString = pigeonVar_list[1] as! String
    let type = pigeonVar_list[2] as! ReclaimApiVerificationExceptionType

    return ReclaimApiVerificationException(
      message: message,
      stackTraceAsString: stackTraceAsString,
      type: type
    )
  }
  func toList() -> [Any?] {
    return [
      message,
      stackTraceAsString,
      type,
    ]
  }
  static func == (lhs: ReclaimApiVerificationException, rhs: ReclaimApiVerificationException) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.message, rhs.message) && MessagesPigeonInternal.deepEquals(lhs.stackTraceAsString, rhs.stackTraceAsString) && MessagesPigeonInternal.deepEquals(lhs.type, rhs.type)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ReclaimApiVerificationException")
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: stackTraceAsString, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: type, hasher: &hasher)
  }

  public var description: String {
    return "ReclaimApiVerificationException(message: \(String(describing: message)), stackTraceAsString: \(String(describing: stackTraceAsString)), type: \(String(describing: type)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReclaimApiVerificationResponse: Hashable, CustomStringConvertible {
  var sessionId: String
  var didSubmitManualVerification: Bool
  var proofs: [[String: Sendable?]]
  var exception: ReclaimApiVerificationException? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReclaimApiVerificationResponse? {
    let sessionId = pigeonVar_list[0] as! String
    let didSubmitManualVerification = pigeonVar_list[1] as! Bool
    let proofs = pigeonVar_list[2] as! [[String: Sendable?]]
    let exception: ReclaimApiVerificationException? = nilOrValue(pigeonVar_list[3])

    return ReclaimApiVerificationResponse(
      sessionId: sessionId,
      didSubmitManualVerification: didSubmitManualVerification,
      proofs: proofs,
      exception: exception
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      didSubmitManualVerification,
      proofs,
      exception,
    ]
  }
  static func == (lhs: ReclaimApiVerificationResponse, rhs: ReclaimApiVerificationResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.didSubmitManualVerification, rhs.didSubmitManualVerification) && MessagesPigeonInternal.deepEquals(lhs.proofs, rhs.proofs) && MessagesPigeonInternal.deepEquals(lhs.exception, rhs.exception)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ReclaimApiVerificationResponse")
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: didSubmitManualVerification, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: proofs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: exception, hasher: &hasher)
  }

  public var description: String {
    return "ReclaimApiVerificationResponse(sessionId: \(String(describing: sessionId)), didSubmitManualVerification: \(String(describing: didSubmitManualVerification)), proofs: \(String(describing: proofs)), exception: \(String(describing: exception)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ClientProviderInformationOverride: Hashable, CustomStringConvertible {
  var providerInformationUrl: String? = nil
  var providerInformationJsonString: String? = nil
  var canFetchProviderInformationFromHost: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ClientProviderInformationOverride? {
    let providerInformationUrl: String? = nilOrValue(pigeonVar_list[0])
    let providerInformationJsonString: String? = nilOrValue(pigeonVar_list[1])
    let canFetchProviderInformationFromHost = pigeonVar_list[2] as! Bool

    return ClientProviderInformationOverride(
      providerInformationUrl: providerInformationUrl,
      providerInformationJsonString: providerInformationJsonString,
      canFetchProviderInformationFromHost: canFetchProviderInformationFromHost
    )
  }
  func toList() -> [Any?] {
    return [
      providerInformationUrl,
      providerInformationJsonString,
      canFetchProviderInformationFromHost,
    ]
  }
  static func == (lhs: ClientProviderInformationOverride, rhs: ClientProviderInformationOverride) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.providerInformationUrl, rhs.providerInformationUrl) && MessagesPigeonInternal.deepEquals(lhs.providerInformationJsonString, rhs.providerInformationJsonString) && MessagesPigeonInternal.deepEquals(lhs.canFetchProviderInformationFromHost, rhs.canFetchProviderInformationFromHost)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ClientProviderInformationOverride")
    MessagesPigeonInternal.deepHash(value: providerInformationUrl, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: providerInformationJsonString, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: canFetchProviderInformationFromHost, hasher: &hasher)
  }

  public var description: String {
    return "ClientProviderInformationOverride(providerInformationUrl: \(String(describing: providerInformationUrl)), providerInformationJsonString: \(String(describing: providerInformationJsonString)), canFetchProviderInformationFromHost: \(String(describing: canFetchProviderInformationFromHost)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ClientFeatureOverrides: Hashable, CustomStringConvertible {
  var cookiePersist: Bool? = nil
  var singleReclaimRequest: Bool? = nil
  var attestorBrowserRpcUrl: String? = nil
  var idleTimeThresholdForManualVerificationTrigger: Int64? = nil
  var sessionTimeoutForManualVerificationTrigger: Int64? = nil
  var isAIFlowEnabled: Bool? = nil
  var manualReviewMessage: String? = nil
  var loginPromptMessage: String? = nil
  var useTEE: Bool? = nil
  var interceptorOptions: String? = nil
  var claimCreationTimeoutDurationInMins: Int64? = nil
  var sessionNoActivityTimeoutDurationInMins: Int64? = nil
  var aiProviderNoActivityTimeoutDurationInSecs: Int64? = nil
  var pageLoadedCompletedDebounceTimeoutMs: Int64? = nil
  var potentialLoginTimeoutS: Int64? = nil
  var screenshotCaptureIntervalSeconds: Int64? = nil
  var teeUrls: String? = nil
  var privacyPolicyUrl: String? = nil
  var termsOfServiceUrl: String? = nil
  var potentialFailureReasonsUrl: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ClientFeatureOverrides? {
    let cookiePersist: Bool? = nilOrValue(pigeonVar_list[0])
    let singleReclaimRequest: Bool? = nilOrValue(pigeonVar_list[1])
    let attestorBrowserRpcUrl: String? = nilOrValue(pigeonVar_list[2])
    let idleTimeThresholdForManualVerificationTrigger: Int64? = nilOrValue(pigeonVar_list[3])
    let sessionTimeoutForManualVerificationTrigger: Int64? = nilOrValue(pigeonVar_list[4])
    let isAIFlowEnabled: Bool? = nilOrValue(pigeonVar_list[5])
    let manualReviewMessage: String? = nilOrValue(pigeonVar_list[6])
    let loginPromptMessage: String? = nilOrValue(pigeonVar_list[7])
    let useTEE: Bool? = nilOrValue(pigeonVar_list[8])
    let interceptorOptions: String? = nilOrValue(pigeonVar_list[9])
    let claimCreationTimeoutDurationInMins: Int64? = nilOrValue(pigeonVar_list[10])
    let sessionNoActivityTimeoutDurationInMins: Int64? = nilOrValue(pigeonVar_list[11])
    let aiProviderNoActivityTimeoutDurationInSecs: Int64? = nilOrValue(pigeonVar_list[12])
    let pageLoadedCompletedDebounceTimeoutMs: Int64? = nilOrValue(pigeonVar_list[13])
    let potentialLoginTimeoutS: Int64? = nilOrValue(pigeonVar_list[14])
    let screenshotCaptureIntervalSeconds: Int64? = nilOrValue(pigeonVar_list[15])
    let teeUrls: String? = nilOrValue(pigeonVar_list[16])
    let privacyPolicyUrl: String? = nilOrValue(pigeonVar_list[17])
    let termsOfServiceUrl: String? = nilOrValue(pigeonVar_list[18])
    let potentialFailureReasonsUrl: String? = nilOrValue(pigeonVar_list[19])

    return ClientFeatureOverrides(
      cookiePersist: cookiePersist,
      singleReclaimRequest: singleReclaimRequest,
      attestorBrowserRpcUrl: attestorBrowserRpcUrl,
      idleTimeThresholdForManualVerificationTrigger: idleTimeThresholdForManualVerificationTrigger,
      sessionTimeoutForManualVerificationTrigger: sessionTimeoutForManualVerificationTrigger,
      isAIFlowEnabled: isAIFlowEnabled,
      manualReviewMessage: manualReviewMessage,
      loginPromptMessage: loginPromptMessage,
      useTEE: useTEE,
      interceptorOptions: interceptorOptions,
      claimCreationTimeoutDurationInMins: claimCreationTimeoutDurationInMins,
      sessionNoActivityTimeoutDurationInMins: sessionNoActivityTimeoutDurationInMins,
      aiProviderNoActivityTimeoutDurationInSecs: aiProviderNoActivityTimeoutDurationInSecs,
      pageLoadedCompletedDebounceTimeoutMs: pageLoadedCompletedDebounceTimeoutMs,
      potentialLoginTimeoutS: potentialLoginTimeoutS,
      screenshotCaptureIntervalSeconds: screenshotCaptureIntervalSeconds,
      teeUrls: teeUrls,
      privacyPolicyUrl: privacyPolicyUrl,
      termsOfServiceUrl: termsOfServiceUrl,
      potentialFailureReasonsUrl: potentialFailureReasonsUrl
    )
  }
  func toList() -> [Any?] {
    return [
      cookiePersist,
      singleReclaimRequest,
      attestorBrowserRpcUrl,
      idleTimeThresholdForManualVerificationTrigger,
      sessionTimeoutForManualVerificationTrigger,
      isAIFlowEnabled,
      manualReviewMessage,
      loginPromptMessage,
      useTEE,
      interceptorOptions,
      claimCreationTimeoutDurationInMins,
      sessionNoActivityTimeoutDurationInMins,
      aiProviderNoActivityTimeoutDurationInSecs,
      pageLoadedCompletedDebounceTimeoutMs,
      potentialLoginTimeoutS,
      screenshotCaptureIntervalSeconds,
      teeUrls,
      privacyPolicyUrl,
      termsOfServiceUrl,
      potentialFailureReasonsUrl,
    ]
  }
  static func == (lhs: ClientFeatureOverrides, rhs: ClientFeatureOverrides) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.cookiePersist, rhs.cookiePersist) && MessagesPigeonInternal.deepEquals(lhs.singleReclaimRequest, rhs.singleReclaimRequest) && MessagesPigeonInternal.deepEquals(lhs.attestorBrowserRpcUrl, rhs.attestorBrowserRpcUrl) && MessagesPigeonInternal.deepEquals(lhs.idleTimeThresholdForManualVerificationTrigger, rhs.idleTimeThresholdForManualVerificationTrigger) && MessagesPigeonInternal.deepEquals(lhs.sessionTimeoutForManualVerificationTrigger, rhs.sessionTimeoutForManualVerificationTrigger) && MessagesPigeonInternal.deepEquals(lhs.isAIFlowEnabled, rhs.isAIFlowEnabled) && MessagesPigeonInternal.deepEquals(lhs.manualReviewMessage, rhs.manualReviewMessage) && MessagesPigeonInternal.deepEquals(lhs.loginPromptMessage, rhs.loginPromptMessage) && MessagesPigeonInternal.deepEquals(lhs.useTEE, rhs.useTEE) && MessagesPigeonInternal.deepEquals(lhs.interceptorOptions, rhs.interceptorOptions) && MessagesPigeonInternal.deepEquals(lhs.claimCreationTimeoutDurationInMins, rhs.claimCreationTimeoutDurationInMins) && MessagesPigeonInternal.deepEquals(lhs.sessionNoActivityTimeoutDurationInMins, rhs.sessionNoActivityTimeoutDurationInMins) && MessagesPigeonInternal.deepEquals(lhs.aiProviderNoActivityTimeoutDurationInSecs, rhs.aiProviderNoActivityTimeoutDurationInSecs) && MessagesPigeonInternal.deepEquals(lhs.pageLoadedCompletedDebounceTimeoutMs, rhs.pageLoadedCompletedDebounceTimeoutMs) && MessagesPigeonInternal.deepEquals(lhs.potentialLoginTimeoutS, rhs.potentialLoginTimeoutS) && MessagesPigeonInternal.deepEquals(lhs.screenshotCaptureIntervalSeconds, rhs.screenshotCaptureIntervalSeconds) && MessagesPigeonInternal.deepEquals(lhs.teeUrls, rhs.teeUrls) && MessagesPigeonInternal.deepEquals(lhs.privacyPolicyUrl, rhs.privacyPolicyUrl) && MessagesPigeonInternal.deepEquals(lhs.termsOfServiceUrl, rhs.termsOfServiceUrl) && MessagesPigeonInternal.deepEquals(lhs.potentialFailureReasonsUrl, rhs.potentialFailureReasonsUrl)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ClientFeatureOverrides")
    MessagesPigeonInternal.deepHash(value: cookiePersist, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: singleReclaimRequest, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: attestorBrowserRpcUrl, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: idleTimeThresholdForManualVerificationTrigger, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sessionTimeoutForManualVerificationTrigger, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isAIFlowEnabled, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: manualReviewMessage, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: loginPromptMessage, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: useTEE, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: interceptorOptions, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: claimCreationTimeoutDurationInMins, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sessionNoActivityTimeoutDurationInMins, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: aiProviderNoActivityTimeoutDurationInSecs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: pageLoadedCompletedDebounceTimeoutMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: potentialLoginTimeoutS, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: screenshotCaptureIntervalSeconds, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: teeUrls, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: privacyPolicyUrl, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: termsOfServiceUrl, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: potentialFailureReasonsUrl, hasher: &hasher)
  }

  public var description: String {
    return "ClientFeatureOverrides(cookiePersist: \(String(describing: cookiePersist)), singleReclaimRequest: \(String(describing: singleReclaimRequest)), attestorBrowserRpcUrl: \(String(describing: attestorBrowserRpcUrl)), idleTimeThresholdForManualVerificationTrigger: \(String(describing: idleTimeThresholdForManualVerificationTrigger)), sessionTimeoutForManualVerificationTrigger: \(String(describing: sessionTimeoutForManualVerificationTrigger)), isAIFlowEnabled: \(String(describing: isAIFlowEnabled)), manualReviewMessage: \(String(describing: manualReviewMessage)), loginPromptMessage: \(String(describing: loginPromptMessage)), useTEE: \(String(describing: useTEE)), interceptorOptions: \(String(describing: interceptorOptions)), claimCreationTimeoutDurationInMins: \(String(describing: claimCreationTimeoutDurationInMins)), sessionNoActivityTimeoutDurationInMins: \(String(describing: sessionNoActivityTimeoutDurationInMins)), aiProviderNoActivityTimeoutDurationInSecs: \(String(describing: aiProviderNoActivityTimeoutDurationInSecs)), pageLoadedCompletedDebounceTimeoutMs: \(String(describing: pageLoadedCompletedDebounceTimeoutMs)), potentialLoginTimeoutS: \(String(describing: potentialLoginTimeoutS)), screenshotCaptureIntervalSeconds: \(String(describing: screenshotCaptureIntervalSeconds)), teeUrls: \(String(describing: teeUrls)), privacyPolicyUrl: \(String(describing: privacyPolicyUrl)), termsOfServiceUrl: \(String(describing: termsOfServiceUrl)), potentialFailureReasonsUrl: \(String(describing: potentialFailureReasonsUrl)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ClientLogConsumerOverride: Hashable, CustomStringConvertible {
  var enableLogHandler: Bool
  var canSdkCollectTelemetry: Bool
  var canSdkPrintLogs: Bool? = nil
  var logLevel: String? = nil
  var canLogMetadata: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ClientLogConsumerOverride? {
    let enableLogHandler = pigeonVar_list[0] as! Bool
    let canSdkCollectTelemetry = pigeonVar_list[1] as! Bool
    let canSdkPrintLogs: Bool? = nilOrValue(pigeonVar_list[2])
    let logLevel: String? = nilOrValue(pigeonVar_list[3])
    let canLogMetadata: Bool? = nilOrValue(pigeonVar_list[4])

    return ClientLogConsumerOverride(
      enableLogHandler: enableLogHandler,
      canSdkCollectTelemetry: canSdkCollectTelemetry,
      canSdkPrintLogs: canSdkPrintLogs,
      logLevel: logLevel,
      canLogMetadata: canLogMetadata
    )
  }
  func toList() -> [Any?] {
    return [
      enableLogHandler,
      canSdkCollectTelemetry,
      canSdkPrintLogs,
      logLevel,
      canLogMetadata,
    ]
  }
  static func == (lhs: ClientLogConsumerOverride, rhs: ClientLogConsumerOverride) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.enableLogHandler, rhs.enableLogHandler) && MessagesPigeonInternal.deepEquals(lhs.canSdkCollectTelemetry, rhs.canSdkCollectTelemetry) && MessagesPigeonInternal.deepEquals(lhs.canSdkPrintLogs, rhs.canSdkPrintLogs) && MessagesPigeonInternal.deepEquals(lhs.logLevel, rhs.logLevel) && MessagesPigeonInternal.deepEquals(lhs.canLogMetadata, rhs.canLogMetadata)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ClientLogConsumerOverride")
    MessagesPigeonInternal.deepHash(value: enableLogHandler, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: canSdkCollectTelemetry, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: canSdkPrintLogs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: logLevel, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: canLogMetadata, hasher: &hasher)
  }

  public var description: String {
    return "ClientLogConsumerOverride(enableLogHandler: \(String(describing: enableLogHandler)), canSdkCollectTelemetry: \(String(describing: canSdkCollectTelemetry)), canSdkPrintLogs: \(String(describing: canSdkPrintLogs)), logLevel: \(String(describing: logLevel)), canLogMetadata: \(String(describing: canLogMetadata)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ClientReclaimSessionManagementOverride: Hashable, CustomStringConvertible {
  var enableSdkSessionManagement: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ClientReclaimSessionManagementOverride? {
    let enableSdkSessionManagement = pigeonVar_list[0] as! Bool

    return ClientReclaimSessionManagementOverride(
      enableSdkSessionManagement: enableSdkSessionManagement
    )
  }
  func toList() -> [Any?] {
    return [
      enableSdkSessionManagement
    ]
  }
  static func == (lhs: ClientReclaimSessionManagementOverride, rhs: ClientReclaimSessionManagementOverride) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.enableSdkSessionManagement, rhs.enableSdkSessionManagement)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ClientReclaimSessionManagementOverride")
    MessagesPigeonInternal.deepHash(value: enableSdkSessionManagement, hasher: &hasher)
  }

  public var description: String {
    return "ClientReclaimSessionManagementOverride(enableSdkSessionManagement: \(String(describing: enableSdkSessionManagement)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ClientReclaimAppInfoOverride: Hashable, CustomStringConvertible {
  var appName: String
  var appImageUrl: String
  var isRecurring: Bool
  var theme: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ClientReclaimAppInfoOverride? {
    let appName = pigeonVar_list[0] as! String
    let appImageUrl = pigeonVar_list[1] as! String
    let isRecurring = pigeonVar_list[2] as! Bool
    let theme: String? = nilOrValue(pigeonVar_list[3])

    return ClientReclaimAppInfoOverride(
      appName: appName,
      appImageUrl: appImageUrl,
      isRecurring: isRecurring,
      theme: theme
    )
  }
  func toList() -> [Any?] {
    return [
      appName,
      appImageUrl,
      isRecurring,
      theme,
    ]
  }
  static func == (lhs: ClientReclaimAppInfoOverride, rhs: ClientReclaimAppInfoOverride) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.appName, rhs.appName) && MessagesPigeonInternal.deepEquals(lhs.appImageUrl, rhs.appImageUrl) && MessagesPigeonInternal.deepEquals(lhs.isRecurring, rhs.isRecurring) && MessagesPigeonInternal.deepEquals(lhs.theme, rhs.theme)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ClientReclaimAppInfoOverride")
    MessagesPigeonInternal.deepHash(value: appName, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: appImageUrl, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isRecurring, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: theme, hasher: &hasher)
  }

  public var description: String {
    return "ClientReclaimAppInfoOverride(appName: \(String(describing: appName)), appImageUrl: \(String(describing: appImageUrl)), isRecurring: \(String(describing: isRecurring)), theme: \(String(describing: theme)))"
  }
}

/// Identification information of a session.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ReclaimSessionIdentityUpdate: Hashable, CustomStringConvertible {
  /// The application id.
  var appId: String
  /// The provider id.
  var providerId: String
  /// The session id.
  var sessionId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReclaimSessionIdentityUpdate? {
    let appId = pigeonVar_list[0] as! String
    let providerId = pigeonVar_list[1] as! String
    let sessionId = pigeonVar_list[2] as! String

    return ReclaimSessionIdentityUpdate(
      appId: appId,
      providerId: providerId,
      sessionId: sessionId
    )
  }
  func toList() -> [Any?] {
    return [
      appId,
      providerId,
      sessionId,
    ]
  }
  static func == (lhs: ReclaimSessionIdentityUpdate, rhs: ReclaimSessionIdentityUpdate) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.appId, rhs.appId) && MessagesPigeonInternal.deepEquals(lhs.providerId, rhs.providerId) && MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ReclaimSessionIdentityUpdate")
    MessagesPigeonInternal.deepHash(value: appId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: providerId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
  }

  public var description: String {
    return "ReclaimSessionIdentityUpdate(appId: \(String(describing: appId)), providerId: \(String(describing: providerId)), sessionId: \(String(describing: sessionId)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReclaimApiVerificationOptions: Hashable, CustomStringConvertible {
  /// Whether to delete cookies before user journey starts in the client web view.
  /// Defaults to true.
  var canDeleteCookiesBeforeVerificationStarts: Bool
  /// Whether module can use a callback to host that returns an authentication request when a Reclaim HTTP provider is provided.
  /// Defaults to false.
  /// {@macro CreateClaimOptions.attestorAuthenticationRequest}
  var canUseAttestorAuthenticationRequest: Bool
  var claimCreationType: ClaimCreationTypeApi
  /// Whether module can auto submit the claim.
  /// Defaults to true.
  var canAutoSubmit: Bool
  /// Whether the close button is visible.
  /// Defaults to true.
  var isCloseButtonVisible: Bool
  /// A language code & Country code for localization that should be enforced in the verification flow.
  var locale: String? = nil
  /// Enables use of Reclaim's TEE+MPC protocol for HTTP Request claim verification and
  /// attestation.
  ///
  /// When set to `true`, the verification will use Trusted Execution Environment
  /// (TEE) with Multi-Party Computation (MPC) for enhanced security.
  ///
  /// When set to `false`, the standard Reclaim's proxy attestor verification flow is used.
  ///
  /// When `null` (default), the backend decides whether to use TEE based on
  /// a feature flag (currently in staged rollout).
  var useTeeOperator: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReclaimApiVerificationOptions? {
    let canDeleteCookiesBeforeVerificationStarts = pigeonVar_list[0] as! Bool
    let canUseAttestorAuthenticationRequest = pigeonVar_list[1] as! Bool
    let claimCreationType = pigeonVar_list[2] as! ClaimCreationTypeApi
    let canAutoSubmit = pigeonVar_list[3] as! Bool
    let isCloseButtonVisible = pigeonVar_list[4] as! Bool
    let locale: String? = nilOrValue(pigeonVar_list[5])
    let useTeeOperator: Bool? = nilOrValue(pigeonVar_list[6])

    return ReclaimApiVerificationOptions(
      canDeleteCookiesBeforeVerificationStarts: canDeleteCookiesBeforeVerificationStarts,
      canUseAttestorAuthenticationRequest: canUseAttestorAuthenticationRequest,
      claimCreationType: claimCreationType,
      canAutoSubmit: canAutoSubmit,
      isCloseButtonVisible: isCloseButtonVisible,
      locale: locale,
      useTeeOperator: useTeeOperator
    )
  }
  func toList() -> [Any?] {
    return [
      canDeleteCookiesBeforeVerificationStarts,
      canUseAttestorAuthenticationRequest,
      claimCreationType,
      canAutoSubmit,
      isCloseButtonVisible,
      locale,
      useTeeOperator,
    ]
  }
  static func == (lhs: ReclaimApiVerificationOptions, rhs: ReclaimApiVerificationOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.canDeleteCookiesBeforeVerificationStarts, rhs.canDeleteCookiesBeforeVerificationStarts) && MessagesPigeonInternal.deepEquals(lhs.canUseAttestorAuthenticationRequest, rhs.canUseAttestorAuthenticationRequest) && MessagesPigeonInternal.deepEquals(lhs.claimCreationType, rhs.claimCreationType) && MessagesPigeonInternal.deepEquals(lhs.canAutoSubmit, rhs.canAutoSubmit) && MessagesPigeonInternal.deepEquals(lhs.isCloseButtonVisible, rhs.isCloseButtonVisible) && MessagesPigeonInternal.deepEquals(lhs.locale, rhs.locale) && MessagesPigeonInternal.deepEquals(lhs.useTeeOperator, rhs.useTeeOperator)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ReclaimApiVerificationOptions")
    MessagesPigeonInternal.deepHash(value: canDeleteCookiesBeforeVerificationStarts, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: canUseAttestorAuthenticationRequest, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: claimCreationType, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: canAutoSubmit, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: isCloseButtonVisible, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: locale, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: useTeeOperator, hasher: &hasher)
  }

  public var description: String {
    return "ReclaimApiVerificationOptions(canDeleteCookiesBeforeVerificationStarts: \(String(describing: canDeleteCookiesBeforeVerificationStarts)), canUseAttestorAuthenticationRequest: \(String(describing: canUseAttestorAuthenticationRequest)), claimCreationType: \(String(describing: claimCreationType)), canAutoSubmit: \(String(describing: canAutoSubmit)), isCloseButtonVisible: \(String(describing: isCloseButtonVisible)), locale: \(String(describing: locale)), useTeeOperator: \(String(describing: useTeeOperator)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ProviderVersionApi: Hashable, CustomStringConvertible {
  var versionExpression: String? = nil
  var resolvedVersion: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ProviderVersionApi? {
    let versionExpression: String? = nilOrValue(pigeonVar_list[0])
    let resolvedVersion: String? = nilOrValue(pigeonVar_list[1])

    return ProviderVersionApi(
      versionExpression: versionExpression,
      resolvedVersion: resolvedVersion
    )
  }
  func toList() -> [Any?] {
    return [
      versionExpression,
      resolvedVersion,
    ]
  }
  static func == (lhs: ProviderVersionApi, rhs: ProviderVersionApi) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.versionExpression, rhs.versionExpression) && MessagesPigeonInternal.deepEquals(lhs.resolvedVersion, rhs.resolvedVersion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ProviderVersionApi")
    MessagesPigeonInternal.deepHash(value: versionExpression, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: resolvedVersion, hasher: &hasher)
  }

  public var description: String {
    return "ProviderVersionApi(versionExpression: \(String(describing: versionExpression)), resolvedVersion: \(String(describing: resolvedVersion)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SessionInitResponseApi: Hashable, CustomStringConvertible {
  var sessionId: String
  var resolvedProviderVersion: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SessionInitResponseApi? {
    let sessionId = pigeonVar_list[0] as! String
    let resolvedProviderVersion: String? = nilOrValue(pigeonVar_list[1])

    return SessionInitResponseApi(
      sessionId: sessionId,
      resolvedProviderVersion: resolvedProviderVersion
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      resolvedProviderVersion,
    ]
  }
  static func == (lhs: SessionInitResponseApi, rhs: SessionInitResponseApi) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.resolvedProviderVersion, rhs.resolvedProviderVersion)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SessionInitResponseApi")
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: resolvedProviderVersion, hasher: &hasher)
  }

  public var description: String {
    return "SessionInitResponseApi(sessionId: \(String(describing: sessionId)), resolvedProviderVersion: \(String(describing: resolvedProviderVersion)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LogEntryApi: Hashable, CustomStringConvertible {
  var sessionId: String? = nil
  var message: String
  var level: Int64
  var dateTimeIso: String
  var source: String
  var error: String? = nil
  var stackTraceAsString: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LogEntryApi? {
    let sessionId: String? = nilOrValue(pigeonVar_list[0])
    let message = pigeonVar_list[1] as! String
    let level = pigeonVar_list[2] as! Int64
    let dateTimeIso = pigeonVar_list[3] as! String
    let source = pigeonVar_list[4] as! String
    let error: String? = nilOrValue(pigeonVar_list[5])
    let stackTraceAsString: String? = nilOrValue(pigeonVar_list[6])

    return LogEntryApi(
      sessionId: sessionId,
      message: message,
      level: level,
      dateTimeIso: dateTimeIso,
      source: source,
      error: error,
      stackTraceAsString: stackTraceAsString
    )
  }
  func toList() -> [Any?] {
    return [
      sessionId,
      message,
      level,
      dateTimeIso,
      source,
      error,
      stackTraceAsString,
    ]
  }
  static func == (lhs: LogEntryApi, rhs: LogEntryApi) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sessionId, rhs.sessionId) && MessagesPigeonInternal.deepEquals(lhs.message, rhs.message) && MessagesPigeonInternal.deepEquals(lhs.level, rhs.level) && MessagesPigeonInternal.deepEquals(lhs.dateTimeIso, rhs.dateTimeIso) && MessagesPigeonInternal.deepEquals(lhs.source, rhs.source) && MessagesPigeonInternal.deepEquals(lhs.error, rhs.error) && MessagesPigeonInternal.deepEquals(lhs.stackTraceAsString, rhs.stackTraceAsString)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LogEntryApi")
    MessagesPigeonInternal.deepHash(value: sessionId, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: message, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: level, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: dateTimeIso, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: source, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: error, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: stackTraceAsString, hasher: &hasher)
  }

  public var description: String {
    return "LogEntryApi(sessionId: \(String(describing: sessionId)), message: \(String(describing: message)), level: \(String(describing: level)), dateTimeIso: \(String(describing: dateTimeIso)), source: \(String(describing: source)), error: \(String(describing: error)), stackTraceAsString: \(String(describing: stackTraceAsString)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ReclaimApiVerificationExceptionType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ReclaimSessionStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ClaimCreationTypeApi(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return ReclaimApiVerificationRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return ReclaimApiVerificationException.fromList(self.readValue() as! [Any?])
    case 134:
      return ReclaimApiVerificationResponse.fromList(self.readValue() as! [Any?])
    case 135:
      return ClientProviderInformationOverride.fromList(self.readValue() as! [Any?])
    case 136:
      return ClientFeatureOverrides.fromList(self.readValue() as! [Any?])
    case 137:
      return ClientLogConsumerOverride.fromList(self.readValue() as! [Any?])
    case 138:
      return ClientReclaimSessionManagementOverride.fromList(self.readValue() as! [Any?])
    case 139:
      return ClientReclaimAppInfoOverride.fromList(self.readValue() as! [Any?])
    case 140:
      return ReclaimSessionIdentityUpdate.fromList(self.readValue() as! [Any?])
    case 141:
      return ReclaimApiVerificationOptions.fromList(self.readValue() as! [Any?])
    case 142:
      return ProviderVersionApi.fromList(self.readValue() as! [Any?])
    case 143:
      return SessionInitResponseApi.fromList(self.readValue() as! [Any?])
    case 144:
      return LogEntryApi.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ReclaimApiVerificationExceptionType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ReclaimSessionStatus {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ClaimCreationTypeApi {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? ReclaimApiVerificationRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ReclaimApiVerificationException {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ReclaimApiVerificationResponse {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? ClientProviderInformationOverride {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? ClientFeatureOverrides {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? ClientLogConsumerOverride {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? ClientReclaimSessionManagementOverride {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? ClientReclaimAppInfoOverride {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? ReclaimSessionIdentityUpdate {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? ReclaimApiVerificationOptions {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? ProviderVersionApi {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? SessionInitResponseApi {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? LogEntryApi {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}



/// Apis implemented by the Reclaim module for use by the host.
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ReclaimModuleApiProtocol {
  func startVerification(request requestArg: ReclaimApiVerificationRequest, completion: @escaping (Result<ReclaimApiVerificationResponse, PigeonError>) -> Void)
  func startVerificationFromUrl(url urlArg: String, completion: @escaping (Result<ReclaimApiVerificationResponse, PigeonError>) -> Void)
  func startVerificationFromJson(template templateArg: [AnyHashable?: Sendable?], completion: @escaping (Result<ReclaimApiVerificationResponse, PigeonError>) -> Void)
  func setOverrides(provider providerArg: ClientProviderInformationOverride?, feature featureArg: ClientFeatureOverrides?, logConsumer logConsumerArg: ClientLogConsumerOverride?, sessionManagement sessionManagementArg: ClientReclaimSessionManagementOverride?, appInfo appInfoArg: ClientReclaimAppInfoOverride?, capabilityAccessToken capabilityAccessTokenArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func clearAllOverrides(completion: @escaping (Result<Void, PigeonError>) -> Void)
  func setVerificationOptions(options optionsArg: ReclaimApiVerificationOptions?, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func sendLog(entry entryArg: LogEntryApi, completion: @escaping (Result<Bool, PigeonError>) -> Void)
  func setConsoleLogging(enabled enabledArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func ping(completion: @escaping (Result<Bool, PigeonError>) -> Void)
}
class ReclaimModuleApi: ReclaimModuleApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  func startVerification(request requestArg: ReclaimApiVerificationRequest, completion: @escaping (Result<ReclaimApiVerificationResponse, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reclaim_verifier_module.ReclaimModuleApi.startVerification\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([requestArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! ReclaimApiVerificationResponse
        completion(.success(result))
      }
    }
  }
  func startVerificationFromUrl(url urlArg: String, completion: @escaping (Result<ReclaimApiVerificationResponse, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reclaim_verifier_module.ReclaimModuleApi.startVerificationFromUrl\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([urlArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! ReclaimApiVerificationResponse
        completion(.success(result))
      }
    }
  }
  func startVerificationFromJson(template templateArg: [AnyHashable?: Sendable?], completion: @escaping (Result<ReclaimApiVerificationResponse, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reclaim_verifier_module.ReclaimModuleApi.startVerificationFromJson\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([templateArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! ReclaimApiVerificationResponse
        completion(.success(result))
      }
    }
  }
  func setOverrides(provider providerArg: ClientProviderInformationOverride?, feature featureArg: ClientFeatureOverrides?, logConsumer logConsumerArg: ClientLogConsumerOverride?, sessionManagement sessionManagementArg: ClientReclaimSessionManagementOverride?, appInfo appInfoArg: ClientReclaimAppInfoOverride?, capabilityAccessToken capabilityAccessTokenArg: String?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reclaim_verifier_module.ReclaimModuleApi.setOverrides\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([providerArg, featureArg, logConsumerArg, sessionManagementArg, appInfoArg, capabilityAccessTokenArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func clearAllOverrides(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reclaim_verifier_module.ReclaimModuleApi.clearAllOverrides\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func setVerificationOptions(options optionsArg: ReclaimApiVerificationOptions?, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reclaim_verifier_module.ReclaimModuleApi.setVerificationOptions\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([optionsArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func sendLog(entry entryArg: LogEntryApi, completion: @escaping (Result<Bool, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reclaim_verifier_module.ReclaimModuleApi.sendLog\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([entryArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! Bool
        completion(.success(result))
      }
    }
  }
  func setConsoleLogging(enabled enabledArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reclaim_verifier_module.ReclaimModuleApi.setConsoleLogging\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([enabledArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func ping(completion: @escaping (Result<Bool, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.reclaim_verifier_module.ReclaimModuleApi.ping\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else if listResponse[0] == nil {
        completion(.failure(PigeonError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! Bool
        completion(.success(result))
      }
    }
  }
}
/// Apis implemented by the host using the Reclaim module.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ReclaimHostOverridesApi {
  func onLogs(logJsonString: String, completion: @escaping (Result<Void, Error>) -> Void)
  func createSession(appId: String, providerId: String, timestamp: String, signature: String, providerVersion: String, completion: @escaping (Result<SessionInitResponseApi, Error>) -> Void)
  func updateSession(sessionId: String, status: ReclaimSessionStatus, metadata: [String: Sendable?]?, completion: @escaping (Result<Bool, Error>) -> Void)
  func logSession(appId: String, providerId: String, sessionId: String, logType: String, metadata: [String: Sendable?]?, completion: @escaping (Result<Void, Error>) -> Void)
  func onSessionIdentityUpdate(update: ReclaimSessionIdentityUpdate?, completion: @escaping (Result<Void, Error>) -> Void)
  func fetchProviderInformation(appId: String, providerId: String, sessionId: String, signature: String, timestamp: String, resolvedVersion: String, completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ReclaimHostOverridesApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ReclaimHostOverridesApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ReclaimHostOverridesApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let onLogsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.reclaim_verifier_module.ReclaimHostOverridesApi.onLogs\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onLogsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let logJsonStringArg = args[0] as! String
        api.onLogs(logJsonString: logJsonStringArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      onLogsChannel.setMessageHandler(nil)
    }
    let createSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.reclaim_verifier_module.ReclaimHostOverridesApi.createSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appIdArg = args[0] as! String
        let providerIdArg = args[1] as! String
        let timestampArg = args[2] as! String
        let signatureArg = args[3] as! String
        let providerVersionArg = args[4] as! String
        api.createSession(appId: appIdArg, providerId: providerIdArg, timestamp: timestampArg, signature: signatureArg, providerVersion: providerVersionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      createSessionChannel.setMessageHandler(nil)
    }
    let updateSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.reclaim_verifier_module.ReclaimHostOverridesApi.updateSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let statusArg = args[1] as! ReclaimSessionStatus
        let metadataArg: [String: Any?]? = nilOrValue(args[2])
        api.updateSession(sessionId: sessionIdArg, status: statusArg, metadata: metadataArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateSessionChannel.setMessageHandler(nil)
    }
    let logSessionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.reclaim_verifier_module.ReclaimHostOverridesApi.logSession\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      logSessionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appIdArg = args[0] as! String
        let providerIdArg = args[1] as! String
        let sessionIdArg = args[2] as! String
        let logTypeArg = args[3] as! String
        let metadataArg: [String: Sendable?]? = nilOrValue(args[4])
        api.logSession(appId: appIdArg, providerId: providerIdArg, sessionId: sessionIdArg, logType: logTypeArg, metadata: metadataArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      logSessionChannel.setMessageHandler(nil)
    }
    let onSessionIdentityUpdateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.reclaim_verifier_module.ReclaimHostOverridesApi.onSessionIdentityUpdate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      onSessionIdentityUpdateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let updateArg: ReclaimSessionIdentityUpdate? = nilOrValue(args[0])
        api.onSessionIdentityUpdate(update: updateArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      onSessionIdentityUpdateChannel.setMessageHandler(nil)
    }
    let fetchProviderInformationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.reclaim_verifier_module.ReclaimHostOverridesApi.fetchProviderInformation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchProviderInformationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let appIdArg = args[0] as! String
        let providerIdArg = args[1] as! String
        let sessionIdArg = args[2] as! String
        let signatureArg = args[3] as! String
        let timestampArg = args[4] as! String
        let resolvedVersionArg = args[5] as! String
        api.fetchProviderInformation(appId: appIdArg, providerId: providerIdArg, sessionId: sessionIdArg, signature: signatureArg, timestamp: timestampArg, resolvedVersion: resolvedVersionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchProviderInformationChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ReclaimHostVerificationApi {
  func fetchAttestorAuthenticationRequest(reclaimHttpProvider: [AnyHashable?: Sendable?], completion: @escaping (Result<String, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ReclaimHostVerificationApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `ReclaimHostVerificationApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ReclaimHostVerificationApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let fetchAttestorAuthenticationRequestChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.reclaim_verifier_module.ReclaimHostVerificationApi.fetchAttestorAuthenticationRequest\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      fetchAttestorAuthenticationRequestChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let reclaimHttpProviderArg = args[0] as! [AnyHashable?: Sendable?]
        api.fetchAttestorAuthenticationRequest(reclaimHttpProvider: reclaimHttpProviderArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      fetchAttestorAuthenticationRequestChannel.setMessageHandler(nil)
    }
  }
}
