# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SwiftUIWithPodExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # pod 'ReclaimInAppSdk', '~> 0.10.7-dev.1'
  pod 'ReclaimInAppSdk', :path => '../../'
  # pod 'ReclaimInAppSdk', :git => 'https://github.com/reclaimprotocol/reclaim-inapp-ios-sdk.git', :tag => '0.10.7-dev.1'

  # Pods for SwiftUIWithPodExample

  target 'SwiftUIWithPodExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftUIWithPodExampleUITests' do
    # Pods for testing
  end

end
